### ISSUE TITLE
Could I ask where or how the quotes are generated

### ISSUE THREAD

**Issue by mikeysan** [tintindas/quotes-api#3]
What I am wondering is whether the quotes are dynamically generated. If yes, how are where from. Or do you find the quotes yourself and save them in a database manually?

**Comment by tintindas** [comment]
The quotes are from a mongo database I created in one of my other projects where I scraped goodreads by author name (not the most efficient way)

Here's a link to that repo
[Goodreads Quote Scraper](https://github.com/tintindas/goodreads-quote-scraper)

**Comment by mikeysan** [comment]
Ah! That's fantastic. Thank you. I wondered about it, because I did something similar, but I was using manually generated text in a text file. I will check out the scraper.
